version: "3"
services:
  registry:
    image: "registry:2"
    hostname: "registry"
    ports:
    - "5000:5000"
    volumes:
    - /mnt/registry/:/var/lib/registry
    - /mnt/registry/auth:/auth
    environment:
    - REGISTRY_AUTH=htpasswd
    - REGISTRY_AUTH_HTPASSWD_REALM=Curso Docker
    - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    restart: always
